### ISSUE TITLE
browserify().transform('node-lessify') throws a syntax error

### ISSUE THREAD

**Issue by oncletom** [wilson428/node-lessify#11]
Hello :-)

I have tried to user `node-lessify` with a programmatically use of browserify (inside a gulp task).
So far, I have 2 files:

```js
// index.js
'use strict';

require('./src/stylesheet.css');
```

```css
/* empty file */
```

And then I browserify index.js:

```js
var browserify = require('browserify');

browserify('./index.js')
  .transform('node-lessify')
  .bundle()
  .pipe(gulp.dest('./dist'));
```

This triggers the following error:

```
node-lessify encountered an error when compiling /Users/thomaspa/Projects/ui-pick/stylesheets/style.less
Error:  Missing closing ')', line 1, column 10: ",(function() { var head = document.getElementsByTagName('head')[0]; style = document.createElement('style'); style.type = 'text/css';var css = "";if (style.styleSheet){ style.styleSheet.cssText = css; } else { style.appendChild(document.createTextNode(css)); } head.appendChild(style);}()),"
```

Same problem, either the file is empty or contains some real code.

Any idea what I am doing wrong?

Thanks :-)

**Comment by wilson428** [comment]
I saw this yesterday as well -- possible that I introduced an error. Are you cloning or installing from npm? v0.0.8 might work for you better, though v.0.0.9 is passing tests. Will hunt it down. Thanks!

**Comment by oncletom** [comment]
Installing from npm, w/ browserify v6 (and now v8.1.1). I switched to `lessify` and it works fine.

What are the differences between the two projects by the way?

Thanks :-)

**Comment by oncletom** [comment]
Oh and by the way, when I run the code through browserify command line, with the `package.json` transform config, everything works fine.

```
  "browserify": {
    "transform": [
      "reactify",
      "node-lessify"
    ]
  },
```

**Comment by oncletom** [comment]
Oh wait, actually the problem arises in combination of the `reactify` transform. Needs some more investigations.

**Comment by wilson428** [comment]
Thx for details. I was definitely seeing this yesterday as well when messing around with global option.

**Comment by oncletom** [comment]
Nah I need to sleep, the transform alone through the API causes that issue. I don't really understand why it works from the command line and not from the browserify API. Maybe some env variables are set differently?

**Comment by oncletom** [comment]
Well actually, if the `package.json` contains browserify transforms, thet are automatically applied with browserify programmatic API anyway. The transform was called twice and thus tried to parse the JavaScript wrapper.
