### ISSUE TITLE
Workaround for IE8 max number of stylesheets.

### ISSUE THREAD

**Issue by vladimir-rovensky** [wilson428/node-lessify#15]
Hey guys

I'm having a tough time using node-lessify with IE8 - turns out IE8 will only let you use 31 stylesheets in your page (see http://stackoverflow.com/questions/3211991/does-ie-8-have-a-limit-on-number-of-stylesheets-per-page). Sadly this seems to include style elements created by node-lessify as well. If I require any more styles than that, IE just throws them away. This is really a deal breaker, since I'd like to have a separate less file for each of my components for modularity. Hitting the 31-ish limit is really easy.

Could you perhaps add an option to add the generated styles into a single <style> element to work around this? IE8 also limits the max number of rules in a stylesheet to 4096, but this limit is at least harder to hit.

In case you know of a different workaround for this, I'd appreciate any help.
Thanks

**Comment by wilson428** [comment]
It should be fairly easy for you to do this yourself with `textMode`, which just returns the compiled CSS as a string instead of appending it to the DOM. You can then concat them yourself and append. Or feel free to send me a PR. I don't personally support IE8.

**Comment by vladimir-rovensky** [comment]
Could you elaborate a bit on the solution with textMode? I reckon I'd have to bulk require all my less files in a build script (gulp/grunt), then concat them in a single file which I'd then reference from the page? That seems to kinda defeat the purpose of using a tool like this, doesn't it? It seems closer to the normal way of bundling stylesheets.

**Comment by wilson428** [comment]
I think you may be fighting the framework here. If you have more than 31 stylesheets, you should really be concating them ahead of time. This module supports `@import` if you could import them into a smaller number of files and just request those ones.

**Comment by wilson428** [comment]
Closing for now, but feel free to reopen if you have trouble with that solution.
