### ISSUE TITLE
Resolve node_modules paths in addition to relative paths

### ISSUE THREAD

**Issue by gdw2** [wilson428/node-lessify#3]
I'd like to be able to

    require('multiselect/css/multi-select.css')

instead of (or in addition to) the relative path

    require('./node_modules/multiselect/css/multi-select.css')

Would this be hard to implement?

**Comment by motiz88** [comment]
Just ran into this myself, and apparently, browserify just skips transforms within `node_modules` paths entirely, by design. The solution in this case would be to configure `node-lessify` as a _global_ transform.

From https://github.com/substack/node-browserify#btransformtr-opts:
> If `opts.global` is `true`, the transform will operate on ALL files, despite whether they exist up a level in a `node_modules/` directory. Use global transforms cautiously and sparingly, since most of the time an ordinary transform will suffice. You can also not configure global transforms in a `package.json` like you can with ordinary transforms.

**Comment by wilson428** [comment]
Yep, global is the way to go if you want this. Though I don't full understand this line from the documentation:

> You can also not configure global transforms in a package.json like you can with ordinary transforms.
