### ISSUE TITLE
Possible to define variables and reference them from a different file?

### ISSUE THREAD

**Issue by chevett** [wilson428/node-lessify#9]
Is it possible to have a top level file with a bunch of variables or functions, let's say `app.less`.  Then I'd like to be able to reference those vars/functions from say `widget.less`.  I might be missing something painfully obvious.  Many thanks.

**Comment by wilson428** [comment]
Got an example for me? Happy to look. Just please verify that what you're attempting works otherwise in Less compiled from command line and included in the page the old-fashioned way.

**Comment by wilson428** [comment]
Closing this for now, feel free to reopen if you have more info.
